// Anchor client factory + pool-state fetch helpers.
// Uses idl.json generated by `anchor build` — see idl.ts for the expected shape.
import * as anchor from '@coral-xyz/anchor'
import { Connection, PublicKey } from '@solana/web3.js'
import NodeWallet from '@coral-xyz/anchor/dist/cjs/nodewallet'
import { BONDING_CURVE_PROGRAM_ID, config, getAdminKeypair } from '../config'
import { IDL as BONDING_CURVE_IDL, BondingCurveIDL } from './idl'

export const connection = new Connection(config.rpcUrl, 'confirmed')

export function adminProvider(): anchor.AnchorProvider {
  const wallet = new NodeWallet(getAdminKeypair())
  return new anchor.AnchorProvider(connection, wallet, { commitment: 'confirmed' })
}

export function bondingCurveProgram(): anchor.Program<BondingCurveIDL> {
  return new anchor.Program<BondingCurveIDL>(
    BONDING_CURVE_IDL,
    BONDING_CURVE_PROGRAM_ID,
    adminProvider(),
  )
}

// ── PDA helpers ────────────────────────────────────────────────────────────
export function globalPda(): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([Buffer.from('global')], BONDING_CURVE_PROGRAM_ID)
}
export function poolPda(mint: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([Buffer.from('pool'), mint.toBuffer()], BONDING_CURVE_PROGRAM_ID)
}
export function solVaultPda(mint: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([Buffer.from('sol_vault'), mint.toBuffer()], BONDING_CURVE_PROGRAM_ID)
}

/** Fetch on-chain pool state for `mint` — returns null if not found. */
export async function fetchPool(mint: PublicKey): Promise<any | null> {
  try {
    const program = bondingCurveProgram()
    const [pool] = poolPda(mint)
    return await (program.account as any).poolState.fetch(pool)
  } catch {
    return null
  }
}
