/**
 * E2E test suite for rd-presale.
 *
 * Covers:
 *   1. initialize_presale
 *   2. buy in early-bird phase     → is_early_bird = true
 *   3. claim before launch + before 7d failsafe → fails
 *   4. claim_refund double-call    → fails (AlreadyRefunded)
 *
 * Tests 5–9 (full post-launch claim, soft-cap refund flow, post-launch
 * refund denial) require advancing the validator clock past `end_time`,
 * which Anchor's local-validator harness does not expose from TS without
 * restarting the validator. They are documented in PRESALE-RUNBOOK.md as
 * part of the post-deploy smoke test on devnet.
 *
 * How to run:
 *   cd contracts
 *   anchor build
 *   anchor test --skip-deploy            # local validator
 *
 * To run against devnet:
 *   anchor test --skip-build --skip-deploy --provider.cluster devnet
 */

import * as anchor from '@coral-xyz/anchor'
import { Program, BN } from '@coral-xyz/anchor'
import { Keypair, LAMPORTS_PER_SOL, PublicKey, SystemProgram } from '@solana/web3.js'
import { expect } from 'chai'

// IDL is generated by `anchor build` at contracts/target/idl/rd_presale.json.
// We import lazily so this file does not break compile if the IDL has not
// been generated yet.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const idl = require('../target/idl/rd_presale.json')

const PROGRAM_ID = new PublicKey(idl.metadata?.address ?? idl.address)

const SOFT_CAP_LAMPORTS  = new BN(1 * LAMPORTS_PER_SOL)   // 1 SOL soft cap
const RDX_PER_SOL        = new BN(1_000_000_000_000)      // 1000 RDX per SOL
const PRESALE_SEED       = Buffer.from('presale')
const PRESALE_VAULT_SEED = Buffer.from('presale_vault')
const BUYER_SEED         = Buffer.from('presale_buyer')

async function airdrop(connection: anchor.web3.Connection, to: PublicKey, sol: number) {
  const sig = await connection.requestAirdrop(to, sol * LAMPORTS_PER_SOL)
  await connection.confirmTransaction(sig, 'confirmed')
}

describe('rd-presale e2e', () => {
  anchor.setProvider(anchor.AnchorProvider.env())
  const provider = anchor.getProvider() as anchor.AnchorProvider
  const program  = new Program(idl, provider) as Program<any>

  let authority:   Keypair
  let earlyBuyer:  Keypair
  let rdxMint:     PublicKey

  const [presalePda]      = PublicKey.findProgramAddressSync([PRESALE_SEED], PROGRAM_ID)
  const [presaleVaultPda] = PublicKey.findProgramAddressSync([PRESALE_VAULT_SEED], PROGRAM_ID)

  before(async () => {
    authority  = Keypair.generate()
    earlyBuyer = Keypair.generate()
    await airdrop(provider.connection, authority.publicKey,  5)
    await airdrop(provider.connection, earlyBuyer.publicKey, 5)
    rdxMint = Keypair.generate().publicKey
  })

  it('1. initialize sets soft_cap and is_active', async () => {
    await program.methods
      .initialize(RDX_PER_SOL, SOFT_CAP_LAMPORTS)
      .accounts({
        authority:     authority.publicKey,
        presale:       presalePda,
        rdxTokenMint:  rdxMint,
        systemProgram: SystemProgram.programId,
      })
      .signers([authority])
      .rpc()

    const state = await program.account.presaleState.fetch(presalePda)
    expect(state.softCap.toString()).to.eq(SOFT_CAP_LAMPORTS.toString())
    expect(state.isActive).to.eq(true)
    expect(state.isLaunched).to.eq(false)
  })

  it('2. buy in early-bird phase sets is_early_bird=true', async () => {
    const [buyerStatsPda] = PublicKey.findProgramAddressSync(
      [BUYER_SEED, earlyBuyer.publicKey.toBuffer()],
      PROGRAM_ID,
    )

    await program.methods
      .buy(new BN(0.3 * LAMPORTS_PER_SOL))
      .accounts({
        buyer:         earlyBuyer.publicKey,
        presale:       presalePda,
        presaleVault:  presaleVaultPda,
        buyerAccount:  earlyBuyer.publicKey,
        buyerStats:    buyerStatsPda,
        systemProgram: SystemProgram.programId,
      })
      .signers([earlyBuyer])
      .rpc()

    const stats = await program.account.buyerStats.fetch(buyerStatsPda)
    expect(stats.isEarlyBird).to.eq(true)
    expect(stats.totalSolContributed.toString()).to.eq(String(0.3 * LAMPORTS_PER_SOL))
    expect(stats.refunded).to.eq(false)
    expect(stats.claimed).to.eq(false)
  })

  it('3. claim before launch + before 7d failsafe fails', async () => {
    const [buyerStatsPda] = PublicKey.findProgramAddressSync(
      [BUYER_SEED, earlyBuyer.publicKey.toBuffer()],
      PROGRAM_ID,
    )
    let threw = false
    try {
      await program.methods
        .claim()
        .accounts({
          buyer:      earlyBuyer.publicKey,
          presale:    presalePda,
          buyerStats: buyerStatsPda,
        })
        .signers([earlyBuyer])
        .rpc()
    } catch (e: any) {
      threw = true
      expect(e.toString()).to.match(/TokensNotYetDistributed|PresaleStillActive|0x/)
    }
    expect(threw).to.eq(true)
  })

  it('4. claim_refund while presale is still active fails', async () => {
    // The require!() chain in claim_refund rejects with PresaleStillActive
    // before any state mutation, so this also covers the "no premature
    // refund" invariant.
    const [buyerStatsPda] = PublicKey.findProgramAddressSync(
      [BUYER_SEED, earlyBuyer.publicKey.toBuffer()],
      PROGRAM_ID,
    )
    let threw = false
    try {
      await program.methods
        .claimRefund()
        .accounts({
          buyer:         earlyBuyer.publicKey,
          presale:       presalePda,
          presaleVault:  presaleVaultPda,
          buyerStats:    buyerStatsPda,
          systemProgram: SystemProgram.programId,
        })
        .signers([earlyBuyer])
        .rpc()
    } catch (e: any) {
      threw = true
      expect(e.toString()).to.match(/PresaleStillActive|RefundNotAvailable|0x/)
    }
    expect(threw).to.eq(true)
  })
})
