[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.15"

[features]
seeds = false
skip-lint = false

[programs.localnet]
rd_fragment = "5CLiUA3yqHNoKAdPeHjeNkipDjjYFPwTpnEFfuR9JxWd"
rd_archive = "6azG6eVkmNxsPAntuK5LzwX2VXaMqsbdTkCpFyHoSJ22"
rd_staking = "B6exebxV6gLVy2J4djeNmULi56uniV9gkogeJfTEo6N9"
rd_rewards = "XhodEAbfkn1GJ37pimGBdUJwgM5aXqfDZ9FAMBPxecg"
rd_treasury = "HpvmQtmxyPeeYKGvKHqEdcnsYUzAQrdynoCX452s2xLz"
rd_token = "CPLCsPQJrfWQgacJEq1QcbwoMcJocbEhjGVmJLPhs38Z"
rd_presale = "HACK1L8hdDN1wuhV5mEbNYGeMXjhFzvz3HNvDTCdFP2a"
rd_governance = "8JJd3isBeCkYtsdwTFFLNRCJJXQbABMRgX67vnVzDvSN"
rd_bondingcurve = "AfkwwBhRsuEzZo74mdbwK8EBwo7VYwc8S1T7hb1RHMAa"

[programs.devnet]
rd_fragment = "5CLiUA3yqHNoKAdPeHjeNkipDjjYFPwTpnEFfuR9JxWd"
rd_archive = "6azG6eVkmNxsPAntuK5LzwX2VXaMqsbdTkCpFyHoSJ22"
rd_staking = "B6exebxV6gLVy2J4djeNmULi56uniV9gkogeJfTEo6N9"
rd_rewards = "XhodEAbfkn1GJ37pimGBdUJwgM5aXqfDZ9FAMBPxecg"
rd_treasury = "HpvmQtmxyPeeYKGvKHqEdcnsYUzAQrdynoCX452s2xLz"
rd_token = "CPLCsPQJrfWQgacJEq1QcbwoMcJocbEhjGVmJLPhs38Z"
rd_presale = "HACK1L8hdDN1wuhV5mEbNYGeMXjhFzvz3HNvDTCdFP2a"
rd_governance = "8JJd3isBeCkYtsdwTFFLNRCJJXQbABMRgX67vnVzDvSN"
rd_bondingcurve = "AfkwwBhRsuEzZo74mdbwK8EBwo7VYwc8S1T7hb1RHMAa"

[programs.mainnet]
rd_fragment = "5CLiUA3yqHNoKAdPeHjeNkipDjjYFPwTpnEFfuR9JxWd"
rd_archive = "6azG6eVkmNxsPAntuK5LzwX2VXaMqsbdTkCpFyHoSJ22"
rd_staking = "B6exebxV6gLVy2J4djeNmULi56uniV9gkogeJfTEo6N9"
rd_rewards = "XhodEAbfkn1GJ37pimGBdUJwgM5aXqfDZ9FAMBPxecg"
rd_treasury = "HpvmQtmxyPeeYKGvKHqEdcnsYUzAQrdynoCX452s2xLz"
rd_token = "CPLCsPQJrfWQgacJEq1QcbwoMcJocbEhjGVmJLPhs38Z"
rd_presale = "HACK1L8hdDN1wuhV5mEbNYGeMXjhFzvz3HNvDTCdFP2a"
rd_governance = "8JJd3isBeCkYtsdwTFFLNRCJJXQbABMRgX67vnVzDvSN"
rd_bondingcurve = "BCurve1111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
